version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app.docker
    image: PROJECT_NAME:app
    command: nodemon SCRIPT_FILE
    container_name: PROJECT_NAME-app
    volumes:
      - ..:/app
    ports:
      - "HOST_PORT:CONTAINER_PORT"